# Generated by Django 3.1.7 on 2021-04-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0004_hubcategoryusers_user'),
        ('authapp', '0002_auto_20210404_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('short_desc', models.CharField(max_length=200, verbose_name='краткое описание')),
                ('post_text', models.TextField(null=True, verbose_name='пост')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('hub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_category', to='hub.hubcategory', verbose_name='подкатегория')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='authapp.hubuserprofile')),
            ],
        ),
    ]
