# Generated by Django 3.1.7 on 2021-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210408_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_karma',
            field=models.IntegerField(default=0, verbose_name='карма поста'),
        ),
    ]
