# Generated by Django 3.1.7 on 2021-04-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_content'),
        ('post', '0004_post_post_karma'),
    ]

    operations = [
    ]
