# Generated by Django 3.1.7 on 2021-04-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210411_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_desc',
        ),
    ]
