# Generated by Django 3.1.7 on 2021-04-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20210411_1810'),
        ('post', '0006_merge_20210411_1013'),
    ]

    operations = [
    ]
