# Generated by Django 3.1.7 on 2021-04-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20210415_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='postkarma',
            options={'ordering': ('-created_at',), 'verbose_name': 'карма поста', 'verbose_name_plural': 'Карма постов'},
        ),
        migrations.AlterField(
            model_name='postkarma',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='post.post', verbose_name='пост'),
        ),
        migrations.AlterField(
            model_name='postkarma',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_karma', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
