# Generated by Django 3.1.7 on 2021-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'опубликован'), ('unpublished', 'неопубликован'), ('archive', 'в архиве'), ('template', 'шаблон')], default='unpublished', max_length=11, verbose_name='статус'),
        ),
    ]
