# Generated by Django 3.1.7 on 2021-04-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210419_2309'),
        ('post', '0015_comment'),
    ]

    operations = [
    ]
