# Generated by Django 3.1.7 on 2021-04-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_comment_published'),
        ('post', '0016_merge_20210419_2322'),
    ]

    operations = [
    ]
