# Generated by Django 3.1.7 on 2021-04-20 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_merge_20210420_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'опубликован'), ('unpublished', 'не опубликован'), ('archive', 'в архиве'), ('template', 'шаблон')], default='unpublished', max_length=11, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='CommentKarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.SmallIntegerField(blank=True, null=True, verbose_name='карма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karma', to='post.comment', verbose_name='комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_karma_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'карма комментария',
                'verbose_name_plural': 'Карма комментариев',
                'ordering': ('-created_at',),
            },
        ),
    ]
