# Generated by Django 3.1.7 on 2021-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20210420_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='karma_count',
            field=models.IntegerField(default=0, verbose_name='количество кармы'),
        ),
    ]
