# Generated by Django 3.1.7 on 2021-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_karma_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='модерация проводилась'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время модерации'),
        ),
        migrations.AddField(
            model_name='post',
            name='need_moderate',
            field=models.BooleanField(default=False, verbose_name='нужна модерация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'опубликован'), ('unpublished', 'не опубликован'), ('archive', 'в архиве'), ('template', 'шаблон'), ('on_moderate', 'на модерации'), ('need_review', 'необходима модерация'), ('moderate_false', 'модерация не пройдена')], default='unpublished', max_length=20, verbose_name='статус'),
        ),
    ]
