# Generated by Django 3.1.7 on 2021-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20210424_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.TextField(max_length=200, verbose_name='тэг поста'),
        ),
    ]
