# Generated by Django 3.1.7 on 2021-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20210425_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='post.Tags', verbose_name='тэги поста'),
        ),
    ]
