# Generated by Django 3.1.7 on 2021-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20210425_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post.Tags', verbose_name='тэги поста'),
        ),
    ]
