# Generated by Django 3.1.7 on 2021-04-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20210426_1526'),
        ('post', '0023_auto_20210425_0128'),
    ]

    operations = [
    ]
