# Generated by Django 3.1.7 on 2021-05-01 18:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_merge_20210427_2226'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'content'], name='post_post_name_853ca0_gin'),
        ),
    ]
