# Generated by Django 3.1.7 on 2021-05-12 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0029_auto_20210501_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_complaint',
            field=models.BooleanField(default=False, verbose_name='есть жалобы'),
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('spam', 'Рассылка спама'), ('violation', 'Нарушение правил сайта'), ('abuse', 'Оскорбления'), ('pron', 'Распространение порнографии')], default='spam', max_length=10, verbose_name='тип жалобы')),
                ('complaint_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='текст жалобы')),
                ('is_satisfied', models.BooleanField(default=False, verbose_name='жалоба удовлетворена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='post.comment', verbose_name='комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'жалоба на комментарий',
                'verbose_name_plural': 'жалобы на комментарии',
                'ordering': ('-created_at', '-comment'),
            },
        ),
    ]
