# Generated by Django 3.1.7 on 2021-05-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20210513_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('spam', 'Рассылка спама'), ('violation', 'Нарушение правил сайта'), ('abuse', 'Оскорбления'), ('pron', 'Распространение порнографии')], default='spam', max_length=30, verbose_name='тип жалобы'),
        ),
    ]
