# Generated by Django 3.1.7 on 2021-05-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_auto_20210514_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcomplaint',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='жалоба обработана'),
        ),
    ]
