# Generated by Django 3.1.7 on 2021-04-07 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210404_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubuser',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='hubuserprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='hubuserprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubuserprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
    ]
