# Generated by Django 3.1.7 on 2021-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210408_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubuserprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'м'), ('F', 'ж')], max_length=1, null=True, verbose_name='пол'),
        ),
    ]
