# Generated by Django 3.1.7 on 2021-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210423_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubuser',
            name='banned_to',
            field=models.DateField(blank=True, null=True, verbose_name='забанен до'),
        ),
        migrations.AlterField(
            model_name='hubuser',
            name='banned',
            field=models.CharField(choices=[('active', 'активный'), ('banned for time', 'временно забанен'), ('banned forever', 'перманентно забанен')], default='active', max_length=15, verbose_name='забанен'),
        ),
    ]
