# Generated by Django 3.1.7 on 2021-04-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210423_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubuser',
            name='banned_to',
        ),
    ]
