# Generated by Django 3.1.7 on 2021-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_hubuser_banned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubuser',
            name='banned_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='забанен до'),
        ),
    ]
