# Generated by Django 3.1.7 on 2021-04-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_hubuser_banned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubuser',
            name='banned',
            field=models.CharField(choices=[('active', 'активный'), ('banned_for_time', 'временно забанен'), ('banned_forever', 'перманентно забанен')], default='active', max_length=15, verbose_name='забанен'),
        ),
    ]
