# Generated by Django 3.1.7 on 2021-05-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210424_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubuser',
            name='rating',
        ),
    ]
