# Generated by Django 3.1.7 on 2021-04-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('short_desc', models.CharField(max_length=150, verbose_name='краткое описание')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='описание')),
                ('tags', models.CharField(blank=True, max_length=300, null=True, verbose_name='тэги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
            ],
        ),
        migrations.CreateModel(
            name='HubCategoryUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='hub.hubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
