# Generated by Django 3.1.7 on 2021-04-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20210403_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubcategoryusers',
            name='user',
        ),
    ]
